config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :twitter_accounts
  root 'twitter_accounts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	
	
end

app/models/tweet_track.rb
class TweetTrack < ApplicationRecord

	def self.update_track(tweet_id , twitter_account_id)
		tweet_track = TweetTrack.where(tweet_id: tweet_id, twitter_account_id: twitter_account_id)
		if tweet_track != []
			times = tweet_track.last.times + 1
			tweet_track.last.update(times: times)
		else
			TweetTrack.create(tweet_id: tweet_id, twitter_account_id: twitter_account_id, times: 1)
		end
	end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord

	FORBIDDEN_WORDS = ["culo", "caca", "tetas"]

	def fav( tweet_id = 0 )
		return if tweet_id == 0 
		client.fav!(tweet_id)
	end

    def write( tweet_id = 0 )
		return if tweet_id == 0 
		client.update(Tweet.find(tweet_id).text)
		TweetTrack.update_track(tweet_id, id)
	end

	private

	def client
		@client ||= Twitter::REST::Client.new do |config|
		  config.consumer_key        = consumer_key
		  config.consumer_secret     = consumer_secret
		  config.access_token        = access_token
		  config.access_token_secret = access_token_secret
		end
	end

	def write_direct_tweet(pass = 0, text = '')
		return if pass != 1976 || text.include?(SELF::FORBIDDEN_WORDS)
		client.update(text)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
  	admin == true
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]


  def index
    @tweet = Tweet.all
  end

  def show
  end

 
  def new
    @tweet = Tweet.new
  end


  def edit
  end


  def create
    @tweet = Tweet.new(test_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.fetch(:tweet, {})
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :set_twitter_account, only: [:show, :edit, :update, :destroy]

  # GET /twitter_accounts
  # GET /twitter_accounts.json
  def index
    @twitter_accounts = TwitterAccount.all
  end

  # GET /twitter_accounts/1
  # GET /twitter_accounts/1.json
  def show
  end

  # GET /twitter_accounts/new
  def new
    @twitter_account = TwitterAccount.new
  end

  # GET /twitter_accounts/1/edit
  def edit
  end

  # POST /twitter_accounts
  # POST /twitter_accounts.json
  def create
    @twitter_account = TwitterAccount.new(twitter_account_params)

    respond_to do |format|
      if @twitter_account.save
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully created.' }
        format.json { render :show, status: :created, location: @twitter_account }
      else
        format.html { render :new }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitter_accounts/1
  # PATCH/PUT /twitter_accounts/1.json
  def update
    respond_to do |format|
      if @twitter_account.update(twitter_account_params)
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_account }
      else
        format.html { render :edit }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_accounts/1
  # DELETE /twitter_accounts/1.json
  def destroy
    @twitter_account.destroy
    respond_to do |format|
      format.html { redirect_to twitter_accounts_url, notice: 'Twitter account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_account
      @twitter_account = TwitterAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_account_params
      params.require(:twitter_account).permit(:name, :account, :consumer_key, :consumer_secret, :access_token, :access_token_secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagrant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweets</h1>

<%= render 'form', test: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', test: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/twitter_accounts/_form.html.erb
<% if current_user.admin? %>
  <%= form_with(model: twitter_account, local: true) do |form| %>
    <% if twitter_account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(twitter_account.errors.count, "error") %> prohibited this twitter_account from being saved:</h2>

        <ul>
        <% twitter_account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :twitter_account_name %>
    </div>

    <div class="field">
      <%= form.label :account %>
      <%= form.text_field :account, id: :twitter_account_account %>
    </div>

    <div class="field">
      <%= form.label :consumer_key %>
      <%= form.text_field :consumer_key, id: :twitter_account_consumer_key %>
    </div>

    <div class="field">
      <%= form.label :consumer_secret %>
      <%= form.text_field :consumer_secret, id: :twitter_account_consumer_secret %>
    </div>

    <div class="field">
      <%= form.label :access_token %>
      <%= form.text_field :access_token, id: :twitter_account_access_token %>
    </div>

    <div class="field">
      <%= form.label :access_token_secret %>
      <%= form.text_field :access_token_secret, id: :twitter_account_access_token_secret %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/twitter_accounts/edit.html.erb
<h1>Editing Twitter Account</h1>

<%= render 'form',  twitter_account:  @twitter_account %>

<%= link_to 'Show', @twitter_account %> |
<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin? %>
  <h1>Twitter Accounts</h1>
  <%= current_user.email %> dfdfdffd<%= current_user.admin %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Account</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @twitter_accounts.each do |twitter_account| %>
        <tr>
          <td><%= twitter_account.name %></td>
          <td><%= twitter_account.account %></td>
         
          <td><%= link_to 'Show', twitter_account %></td>
          <td><%= link_to 'Edit', edit_twitter_account_path(twitter_account) %></td>
          <td><%= link_to 'Destroy', twitter_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Twitter Account', new_twitter_account_path %>
<% end %>

app/views/twitter_accounts/new.html.erb
<h1>New Twitter Account</h1>

<%= render 'form', twitter_account: @twitter_account %>

<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @twitter_account.name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @twitter_account.account %>
</p>

<p>


<%= link_to 'Edit', edit_twitter_account_path(@twitter_account) %> |
<%= link_to 'Back', twitter_accounts_path %>